#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  Nov 10, 2023 04:16:16 AM CST  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    system_shutdown_png "./graphics/system-shutdown.png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #8ba5cc
set vTcl(analog_color_p) #c5cc8b
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightbackground navajowhite3 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1020x760+739+462
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2545 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::style configure TFrame -foreground $vTcl(actual_gui_fg)
    ttk::style configure TFrame -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame "$top.tFr47" \
        -borderwidth 2 -relief groove -width 1015 -height 55 
    vTcl:DefineAlias "$top.tFr47" "TFrame1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.tFr47
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$site_3_0.tBu48" \
        -command "on_btnExit" -takefocus {} -image system_shutdown_png \
        -compound none -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.tBu48" "btnExit" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TLabel -background $vTcl(actual_gui_bg)
    ttk::style configure TLabel -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabel -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::label "$site_3_0.tLa49" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -relief flat -anchor e -justify left -text "Search: " -compound left 
    vTcl:DefineAlias "$site_3_0.tLa49" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$site_3_0.tBu51" \
        -command "on_btnGo" -takefocus {} -text "GO!" -compound left 
    vTcl:DefineAlias "$site_3_0.tBu51" "btnGo" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TEntry -background $vTcl(actual_gui_bg)
    ttk::style configure TEntry -foreground $vTcl(actual_gui_fg)
    ttk::style configure TEntry -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::entry "$site_3_0.tEn47" \
        -font "TkTextFont" -textvariable "search_address" -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn47" "TEntry1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_3_0.tBu48 \
        -in $site_3_0 -x 960 -y 4 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa49 \
        -in $site_3_0 -x 90 -y 20 -width 102 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu51 \
        -in $site_3_0 -x 428 -y 15 -width 83 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn47 \
        -in $site_3_0 -x 194 -y 19 -width 224 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$top.tBu52" \
        -command "on_btnCreateMarker" -takefocus {} -text "Create Marker" \
        -compound left 
    vTcl:DefineAlias "$top.tBu52" "btnCreateMarker" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$top.tBu53" \
        -command "on_btnClearMarkers" -takefocus {} -text "Clear Markers" \
        -compound left 
    vTcl:DefineAlias "$top.tBu53" "btnClearMarkers" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$top.tBu54" \
        -command "on_btnCreatePath" -takefocus {} -text "Create Path" \
        -compound left 
    vTcl:DefineAlias "$top.tBu54" "btnCreatePath" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$top.tBu55" \
        -command "on_btnClearPath" -takefocus {} -text "Clear Path" \
        -compound left 
    vTcl:DefineAlias "$top.tBu55" "btnClearPath" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TLabel -background $vTcl(actual_gui_bg)
    ttk::style configure TLabel -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabel -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::label "$top.tLa56" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 12 -weight bold -slant roman -underline 0 -overstrike 0" \
        -relief flat -anchor center -justify left -text "Markers: " \
        -compound left 
    vTcl:DefineAlias "$top.tLa56" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Scrolledlistbox -background $vTcl(actual_gui_bg)
    ttk::style configure Scrolledlistbox -foreground $vTcl(actual_gui_fg)
    ttk::style configure Scrolledlistbox -font "$vTcl(actual_gui_font_dft_desc)"
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd "$top.scr57" \
        -background navajowhite3 -height 75 -highlightbackground navajowhite3 \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr57" "Scrolledlistbox1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A

    $top.scr57.01 configure -background white \
        -cursor xterm \
        -disabledforeground #9a8668 \
        -exportselection 0 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground navajowhite3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #b9a17d \
        -selectforeground black \
        -width 10
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::style configure TFrame -foreground $vTcl(actual_gui_fg)
    ttk::style configure TFrame -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame "$top.tFr58" \
        -borderwidth 2 -relief groove -width 125 -height 75 
    vTcl:DefineAlias "$top.tFr58" "TFrame2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tFr47 \
        -in $top -x 2 -y 2 -width 1016 -relwidth 0 -height 55 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu52 \
        -in $top -x 30 -y 70 -width 144 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu53 \
        -in $top -x 188 -y 70 -width 144 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu54 \
        -in $top -x 345 -y 70 -width 144 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu55 \
        -in $top -x 504 -y 70 -width 144 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa56 \
        -in $top -x 820 -y 90 -width 173 -relwidth 0 -height 19 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.scr57 \
        -in $top -x 810 -y 120 -width 200 -relwidth 0 -height 278 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.tFr58 \
        -in $top -x 6 -y 120 -width 799 -relwidth 0 -height 599 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

